### ISSUE TITLE
No primal feasible solution

### ISSUE THREAD

**Issue by tminka** [OSeMOSYS/simplicity#4]
When running the commands in the README, `glpsol -m OSeMOSYS.txt -d simplicity.txt` says there is no primal feasible solution.  This is due to the numbers in the data/default_values.csv file.  For example, `ModelPeriodEmissionLimit,-1`

**Comment by willu47** [comment]
Hi @tminka - thanks for the report. Which version of the OSeMOSYS code are you using?  Default values of `-1` were introduced under OSeMOSYS/OSeMOSYS_GNU_MathProg#30 to fix issues with upper bounds of 0 being ignore for certain constraint parameters (OSeMOSYS/OSeMOSYS_GNU_MathProg#13 and OSeMOSYS/OSeMOSYS_GNU_MathProg#26).

You may wish to try a more recent version of the OSeMOSYS GNU MathProg code with this version of the simplicity model.

**Comment by tminka** [comment]
I am using the version of the OSeMOSYS code that I get by default when I clone the OSeMOSYS repository (with submodules).  It is at https://github.com/OSeMOSYS/OSeMOSYS_GNU_MathProg/blob/5daea546643298be9d84b0108e4c2dd8e228ee7b/src/osemosys.txt

**Comment by willu47** [comment]
Hi @tminka - understood.  We haven't yet established a good release system for the whole OSeMOSYS family yet, and so that version of the GNU MathProg code is still rather old.

Please update to the newest version of the GNU MathProg code by following these steps from the root of the OSeMOSYS repository:

```bash
cd OSeMOSYS_GNU_MathProg
git checkout master
git pull
```
This should update the repository for OSeMOSYS_GNU_MathProg with the latest version of the code.

**Comment by tminka** [comment]
Unfortunately the newest version of the GNU MathProg code doesn't work with simplicity since simplicity does not define DiscountRateStorage.  The Training_Case_Studies (atlantis and utopia) have the same problem.

**Comment by willu47** [comment]
Very true - then it is a simple matter to `git checkout xxxxxx` the version of the OSeMOSYS code which does work with simplicity...  1567dbe2d341841c97e6fdb9fa130bd22d66fe83 should be fine.

So try `git checkout 1567dbe2d`.

It's clear we should add better documentation to the simplicity model so that it is less difficult to find a version of the model it is compatible with!

**Comment by tminka** [comment]
Thanks, that works.  I will create a PR to update the documentation.
